name: docker-buildx-push

on:
  push:
    branches:
      - master

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout master
        uses: actions/checkout@master
      -
        name: Build and publish image
        uses: zmingxie/docker_buildx@master
        with:
          publish: true
          imageName: ${{ secrets.IMAGE_NAME }}
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
          tag: latest
